erDiagram

  PASSWORD_RESET_TOKEN {
    string token PK
    int physiotherapistId FK
    datetime expiresAt
  }

  PHYSIOTHERAPIST {
    int id PK
    string email
    string name
    string surname
  }

  PHYSIOTHERAPIST ||--o| PASSWORD_RESET_TOKEN : "té"
