erDiagram

  PNI_REPORT {
    int id PK
    int patientId FK
    date reportDate
    double hoursAsleep
    double avgHr
    int minHr
    int deepSleep
    double continuity
  }

  PATIENT {
    int id PK
    string email
    string legalName
    string surname
  }

  PATIENT ||--o{ PNI_REPORT : "té"
