sequenceDiagram
  actor Client
  participant LogController
  participant LogPhysiotherapistService
  participant CredentialsValidatorPort
  participant TokenGeneratorPort

  Client->>LogController: POST /physiotherapist/login {email, password}
  LogController->>LogPhysiotherapistService: authenticate(email, password)
  LogPhysiotherapistService->>CredentialsValidatorPort: validate(email, password)
  alt Credencials incorrectes
    CredentialsValidatorPort-->>LogPhysiotherapistService: throw BadCredentialsException
    LogPhysiotherapistService-->>LogController: throw BadCredentialsException
    LogController-->>Client: 401 Unauthorized
  else Credencials vàlides
    CredentialsValidatorPort-->>LogPhysiotherapistService: PhysiotherapistDetails
    LogPhysiotherapistService->>TokenGeneratorPort: generateToken(physiotherapistDetails)
    TokenGeneratorPort-->>LogPhysiotherapistService: jwtToken
    LogPhysiotherapistService-->>LogController: AuthenticationResponse{token}
    LogController-->>Client: 200 OK + Header Authorization: Bearer {token}
  end
